### PR TITLE
Bug fixes and feature enhancements

### PR DESCRIPTION
**Pull request by mattallen37**

### CODE REVIEW

**Comment by byWulf** [comment]
@mattallen37 Could you explain, what these constants KD and KR are and what happens, when you make them higher or lower? Can't find anything about them at google :/ Thanks in advance!

**Comment by mattallen37** [comment]
@byWulf See [here](https://forum.dexterindustries.com/t/solved-pid-controller-in-set-motor-dps/3657/2) for an explanation.

**Comment by johnisanerd** [comment]
@mattallen37 maybe you could copy paste that info into the readme so it's easier to find?

**Comment by mattallen37** [comment]
@johnisanerd I added those comments into the drivers in PR #75.

**Comment by johnisanerd** [comment]
@mattallen37 why did we have to point someone to a forum post then?

**Comment by mattallen37** [comment]
@johnisanerd because PR #75 didn't exist at that point. I added the comments and created the PR for people to take advantage of moving forward.

**Comment by johnisanerd** [comment]
Since PR #75 exists now, can we add this explanation into the readme in the balancebot folder?

**Comment by mattallen37** [comment]
The BrickPi3 BalanceBot project doesn't have a readme, and the BalanceBot doesn't use these constants. These constants are used by the FW for controlling the motors when you specify a target position or speed (BalanceBot controls the motor power).

**Pull request merged**
