### PR TITLE
Updates to help non Raspbian for Robot users

### PR DESCRIPTION
**Pull request by Shoban94**

### CODE REVIEW

**Comment by DexterInd** [comment]
@mattallen37 can you please review this?

**Comment by graykevinb** [comment]
I cloned your repo and the script said setup.py is no such file or directory.

**Comment by DexterInd** [comment]
Hey @graykevinb we were just talking about this and I think this will break things for our installation and for other users.  This will break our installation on Raspbian for Robots, for example.

**Comment by graykevinb** [comment]
Could the files be simplified so the brickpi folders would not differ on raspbian_for_robots and raspbian?

**Comment by mattallen37** [comment]
That was the goal; no matter which OS, it would be installed in /home/pi/Dexter/BrickPi3 (even if that meant creating the /home/pi/Dexter directory on standard Raspbian).

**Comment by Shoban94** [comment]
Hi @mattallen37, I have updated the PR, now I have used the command @CleoQc , had mentioned and it works well with both Raspbian for Robots and Raspbian Jessie images. The REPO_PATH is set based on the directory path used to call the script(SCRIPT_PATH) and I restrict the path to BrickPi3, which gives the REPO_PATH . Let me know your comments

**Pull request merged**
